name: Rust

on:
  push:
    branches: [ "master", "develops" ]
  pull_request:
    branches: [ "master", "develops" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpango1.0-dev

    - name: Set environment for pkg-config
      run: echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/lib/pkgconfig:/usr/share/pkgconfig" >> $GITHUB_ENV

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose